from .ClassificationModel import *
from .FCN2s import *
from .FCN4s import *
from .FCN8s import *
from .FCN16s import *
from .FCN32s import *
from .SegNet import *
from .UNet import *
from .DeepLabv3 import *